# Generated by Django 4.1.3 on 2023-11-30 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='tags',
            field=models.ManyToManyField(related_name='places', to='backend.tag'),
        ),
    ]
