# Generated by Django 4.2.10 on 2024-03-02 19:04

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(max_length=255, null=True)),
                ('address', models.CharField(max_length=255, unique=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('tags', models.CharField(max_length=255, unique=True)),
                ('category', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.PROTECT, to='backend.category')),
            ],
            options={
                'verbose_name_plural': 'Locations',
            },
        ),
    ]
