# Generated by Django 4.1.3 on 2023-11-28 20:44

import backend.models
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion

def create_default_category(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Category = apps.get_model("backend", "Category")
    common_category = Category()
    common_category.id = -1
    common_category.name = "Default"
    common_category.save()

class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name_plural': 'Places'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='category',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.RunPython(create_default_category),
        migrations.AddField(
            model_name='place',
            name='category',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.PROTECT, to='backend.category'),
        ),
        migrations.AddField(
            model_name='place',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='category',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.PROTECT, to='backend.category'),
        ),
        migrations.AddField(
            model_name='request',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25, null=True), default=backend.models.get_tags_default, size=None),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='request',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
