# Generated by Django 4.2.8 on 2024-01-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Images',
            },
        ),
    ]
