# Generated by Django 4.2.10 on 2024-03-02 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='description',
        ),
        migrations.AddField(
            model_name='location',
            name='info',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='location',
            name='category',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='location',
            name='tags',
            field=models.CharField(default='', max_length=254),
        ),
    ]
