# Generated by Django 4.2.8 on 2024-01-11 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='images_set_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='images_set_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
