# Generated by Django 4.1.3 on 2023-11-30 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_place_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='addressString',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
