# Generated by Django 4.1.3 on 2023-11-29 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_place_options_remove_category_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
