# Generated by Django 4.2.8 on 2024-01-11 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_place_images_set_id_request_images_set_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='images_set_id',
        ),
        migrations.RemoveField(
            model_name='request',
            name='images_set_id',
        ),
        migrations.AddField(
            model_name='image',
            name='places',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.place'),
        ),
        migrations.AddField(
            model_name='image',
            name='requests',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.request'),
        ),
    ]
