# Generated by Django 4.2.10 on 2024-03-03 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_location_description_location_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='place_id',
            field=models.CharField(default='-1', max_length=10),
            preserve_default=False,
        ),
    ]
