# Generated by Django 4.1.3 on 2023-12-10 07:46

import backend.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50, null=True), default=backend.models.get_tags_default, size=None),
        ),
    ]
