# Generated by Django 4.2.8 on 2024-01-11 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_place_images_set_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='requests',
            new_name='request',
        ),
        migrations.RemoveField(
            model_name='image',
            name='places',
        ),
    ]
