# Generated by Django 4.2.22 on 2026-09-04 06:44
#
# Widens the SubmissionIdempotency operation choices/target constraint for the
# new owner-only media removal and reorder operations, and swaps the managed
# image position constraint from a partial immediate unique index to a
# non-partial deferrable one (a partial index cannot be deferrable, and
# reorder must permute all retained positions in a single transaction). The
# companion ``unmanaged_image_position_null`` check keeps the enforced scope
# identical to the constraint it replaces.

from django.db import migrations, models
import django.db.models.constraints


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_system_draft_expiry'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='image',
            name='unique_managed_image_position',
        ),
        migrations.RemoveConstraint(
            model_name='submissionidempotency',
            name='submission_idempotency_target_matches_operation',
        ),
        migrations.AlterField(
            model_name='submissionidempotency',
            name='operation',
            field=models.CharField(choices=[('submission.create.v3', 'Create submission'), ('submission.edit.v3', 'Edit submission'), ('submission.finalize.v3', 'Finalize submission'), ('submission.expire.v3', 'Expire submission'), ('submission.withdraw.v4', 'Withdraw submission'), ('submission.approve.v4', 'Approve submission'), ('submission.reject.v4', 'Reject submission'), ('media.intent.create.v3', 'Create media intent'), ('media.intent.issue.v3', 'Issue media upload'), ('media.intent.renew.v3', 'Renew media upload'), ('media.intent.verify.v3', 'Verify media upload'), ('media.intent.attach.v3', 'Attach verified media'), ('media.intent.remove.v3', 'Remove attached media'), ('media.intent.expire.v3', 'Expire media intent'), ('media.intent.cleanup.v3', 'Clean up media object'), ('submission.reorder_media.v3', 'Reorder submission media')], max_length=32),
        ),
        migrations.AlterField(
            model_name='submissionlifecycleevent',
            name='operation',
            field=models.CharField(choices=[('submission.create.v3', 'Create submission'), ('submission.edit.v3', 'Edit submission'), ('submission.finalize.v3', 'Finalize submission'), ('submission.expire.v3', 'Expire submission'), ('submission.withdraw.v4', 'Withdraw submission'), ('submission.approve.v4', 'Approve submission'), ('submission.reject.v4', 'Reject submission'), ('media.intent.create.v3', 'Create media intent'), ('media.intent.issue.v3', 'Issue media upload'), ('media.intent.renew.v3', 'Renew media upload'), ('media.intent.verify.v3', 'Verify media upload'), ('media.intent.attach.v3', 'Attach verified media'), ('media.intent.remove.v3', 'Remove attached media'), ('media.intent.expire.v3', 'Expire media intent'), ('media.intent.cleanup.v3', 'Clean up media object'), ('submission.reorder_media.v3', 'Reorder submission media')], max_length=32),
        ),
        migrations.AddConstraint(
            model_name='image',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('request', 'position'), name='unique_managed_image_position'),
        ),
        migrations.AddConstraint(
            model_name='image',
            constraint=models.CheckConstraint(check=models.Q(('is_managed', True), ('position__isnull', True), _connector='OR'), name='unmanaged_image_position_null'),
        ),
        migrations.AddConstraint(
            model_name='submissionidempotency',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('media_intent__isnull', False), ('operation__in', ['media.intent.create.v3', 'media.intent.issue.v3', 'media.intent.renew.v3', 'media.intent.verify.v3', 'media.intent.attach.v3', 'media.intent.remove.v3', 'media.intent.expire.v3', 'media.intent.cleanup.v3'])), models.Q(('media_intent__isnull', True), ('operation__in', ['submission.create.v3', 'submission.edit.v3', 'submission.finalize.v3', 'submission.expire.v3', 'submission.withdraw.v4', 'submission.approve.v4', 'submission.reject.v4', 'submission.reorder_media.v3'])), _connector='OR'), name='submission_idempotency_target_matches_operation'),
        ),
    ]
